.\" mkrootfs.config(5) manual page
.\" See COPYING and COPYRIGHT files for corresponding information.
.Dd September 4, 2023
.Dt MKROOTFS.CONFIG 5
.Os
.\" ==================================================================
.Sh NAME
.Nm mkrootfs.config
.Nd configuration file for mkrootfs
.\" ==================================================================
.Sh SYNOPSIS
.Nm /etc/mkrootfs/config
.\" ==================================================================
.Sh DESCRIPTION
This manual page describes the format of the
.Xr mkrootfs 8 Ns \&'s
configuration file.
.\" ------------------------------------------------------------------
.Ss Syntax
.Sy mkrootfs
configuration file is a list of environment variables.
Each variable must be written in POSIX way, bashism not allowed.
.Pp
Example:
.Bd -literal -offset indent
key=value
.Ed
.Pp
If value contains spaces it must be quoted:
.Bd -literal -offset indent
key="value1 value2"
.Ed
.Pp
If value contains special symbols like
.Ql $ ,
it must be escaped or quoted using single quotes:
.Bd -literal -offset indent
key=\e\e$value
key='$value'
.Ed
.Pp
If line exceeded maximum space on your display and you want to make it
more readable, you can concatenate them:
.Bd -literal -offset indent
key=value
key="${key}value"
.Ed
.Pp
If you want to temporary undefine variable without actually deleting
it, you can simply prepend
.Ql # :
.Bd -literal -offset indent
#key=value
.Ed
.\" ------------------------------------------------------------------
.Ss General Options
The configuration options are as follows:
.Bl -tag -width Ds
.It Sy ROOTFS_DIR Ns = Ns Aq DIR
Specify a rootfs directory instead of the default
.Dq /tmp/rootfs- Ns Ao DATE Ac Ns - Ns Ao ARCH Ac Ns / .
The
.Aq DATE
is the output of
.Dq date +%F ,
and the
.Aq ARCH
is the output of
.Dq uname -m
commands.
.It Sy ROOTFS_TAR Ns = Ns Aq FILE
Specify an output filename (full path is recommended) for compressed
rootfs instead of the default
.Dq Ao ROOTFS_DIR Ac Ns .tar.xz .
.It Sy ROOTFS_LOG Ns = Ns Aq FILE
Specify a log file for
.Xr pkgman 1 Ns \&'s
invocations instead of the default
.Dq Ao ROOTFS_DIR Ac Ns .log .
.It Sy PACKAGES Ns = Ns Aq PKGNAME ...
Specify the packages that will be built and extracted into the
.Aq ROOTFS_DIR .
By default all packages from
.Dq core pkgsrc collection .
.It Sy PKGMK_CONF Ns = Ns Aq FILE
Specify the configuration file for
.Xr pkgmk 8 Ns \&'s
invocations instead of the default
.Pa /etc/pkgmk.conf .
.It Sy PKGMAN_CONF Ns = Ns Aq FILE
Specify the configuration file for
.Xr pkgman 1 Ns \&'s
invocations instead of the default
.Pa /etc/pkgman.conf .
.El
.\" ==================================================================
.Sh FILES
.Bl -tag -width Ds
.It Pa /etc/mkrootfs/config
Configuration file for
.Xr mkrootfs 8 .
.El
.\" ==================================================================
.Sh EXAMPLES
The following configuration file reproduces the defaults: installing
it is equivalent to not having a
.Pa /etc/mkrootfs/config
file at all.
.Bd -literal -offset indent
#
# /etc/mkrootfs/config: mkrootfs(8) configuration
#
# See mkrootfs.conf(5) for more information.
#

# path to the temporary directory for rootfs
ROOTFS_DIR=/tmp/rootfs-$(date +%F)-$(uname -m)

# path to the compressed rootfs tarball
ROOTFS_TAR=$ROOTFS_DIR.tar.xz

# log file for pkgman's invocations
ROOTFS_LOG=$ROOTFS_DIR.log

# build and install all core packages into rootfs dir
PACKAGES=$(pkgman printf %n\e\en \e
           --no-std-config \e
           --config-set="pkgsrcdir /usr/src/pkgsrc-core")

# configuration file for pkgmk's invocations
PKGMK_CONF=/etc/pkgmk.conf

# configuration file for pkgman's invocations
PKGMAN_CONF=/etc/pkgman.conf

# End of file.
.Ed
.\" ==================================================================
.Sh SEE ALSO
.Xr mkrootfs.release 7 ,
.Xr mkrootfs 8
.\" vim: cc=72 tw=70
.\" End of file.
