=pod

=encoding UTF-8

=head1 NAME

mkrootfs.config - configuration file for mkrootfs

=head1 SYNOPSIS

B</etc/mkrootfs/config>

=head1 DESCRIPTION

This manual page describes the format of the L<mkrootfs(8)>'s
configuration file.

B<mkrootfs> configuration file is a list of environment variables.
Each variable must be written in POSIX way, bashism not allowed.

Example:

  key=value

If value contains spaces it must be quoted:

  key="value1 value2"

If value contains special symbols like C<$>, it must be escaped or
quoted using single quotes:

  key=\\$value
  key='$value'

If line exceeded maximum space on your display and you want to make it
more readable, you can concatenate them:

  key=value
  key="${key}value"

If you want to temporary undefine variable without actually deleting
it, you can simply prepend C<#>:

  #key=value

=head1 GENERAL OPTIONS

=over 8

=item B<ROOTFS_DIR>="I<PATH>"

Set directory for root filesystem.

Default: C</tmp/rootfs-{DATE}-{ARCH}>, where C<{DATE}> is the output
of C<date +%F>, and the C<{ARCH}> is the output of C<uname -m>
commands.

=item B<ROOTFS_TAR>="I<FILE>"

Set filename for compressed root filesystem.

Default: C<ROOTFS_DIR>.tar.xz

=item B<ROOTFS_LOG>="I<FILE>"

The log file for L<pkgman(1)>'s invocations.

Default: C<ROOTFS_DIR>.log

=item B<PACKAGES>="I<PKGNAME1> I<PKGNAME2>..."

Packages that will be built and extracted into the C<ROOTFS_DIR>.

Default: all packages from C<core> pkgsrc collection.

=item B<PKGMK_CONF>="I<FILE>"

The configuration file for L<pkgmk(8)>'s invocations.

Default: C</etc/pkgmk.conf>.

=item B<PKGMAN_CONF>="I<FILE>"

The configuration file for L<pkgman(1)>'s invocations.

=back

=head1 EXAMPLE

  #
  # /etc/mkrootfs/config: mkrootfs(8) configuration
  #
  # See mkrootfs.conf(5) for more information.
  #

  # path to the temporary directory for rootfs
  ROOTFS_DIR=/tmp/rootfs-$(date +%F)-$(uname -m)

  # path to the compressed rootfs tarball
  ROOTFS_TAR=$ROOTFS_DIR.tar.xz

  # log file for pkgman's invocations
  ROOTFS_LOG=$ROOTFS_DIR.log

  # build and install all core packages into rootfs dir
  PACKAGES=$(pkgman printf %n\\n \
    --no-std-config --config-set="pkgsrcdir /usr/src/pkgsrc-core")

  # configuration file for pkgmk's invocations
  PKGMK_CONF=/etc/pkgmk.conf

  # configuration file for pkgman's invocations
  PKGMAN_CONF=/etc/pkgman.conf

  # End of file.

=head1 FILES

=over 8

=item F</etc/mkrootfs/config>

Configuration file for L<mkrootfs(8)>.

=back

=head1 SEE ALSO

L<mkrootfs(8)>, L<mkrootfs.release(7)>

=cut

# vim:sw=2:ts=2:sts=2:et:tw=71:cc=72
# End of file.
