#
# /etc/pkgman.conf: configuration file for pkgman(8).
#
# See pkgman.conf(5) for more information.

pkgsrcdir /usr/src/pkgsrc/core
runscripts no
writelog enabled
rmlog_on_success yes
logmode overwrite
logfile logs/%n
makecommand sudo -H -u pkgmk fakeroot pkgmk

# End of file.
