name: Lint CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install lint dependencies
      run: sudo apt-get install -y shellcheck

    - name: Check mkrootfs for errors
      run: cd src && shellcheck -s sh mkrootfs.in

# End of file.
