name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install shellcheck
      run: sudo apt-get install -y shellcheck

    - name: Check mkrootfs script for errors
      run: shellcheck -s sh mkrootfs.in

    - name: Check PODs for errors
      run: podchecker *.pod
